version: '3.8'

services:
  # Backend Spring Boot API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: employee-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - employee-network

  # Frontend React + nginx
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: employee-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - employee-network

networks:
  employee-network:
    driver: bridge